package modelica;

public enum ClassType {
    MODEL,
    PARTIAL_MODEL,
    RECORD,
    PARTIAL_RECORD,
    FUNCTION,
    PARTIAL_FUNCTION,
    PURE_FUNCTION,
    IMPURE_FUNCTION,
    CONNECTOR,
    CLASS,
    PARTIAL_CLASS,
    PARTIAL_CONNECTOR,
    TYPE,
    BLOCK,
    PARTIAL_BLOCK,
    PACKAGE,
    OPERATOR,
    OPERATOR_RECORD,
    OPERATOR_FUNCTION,
    EXPANDABLE_CONNECTOR,
}
