package modelica;

/**
 * Enumeration that holds possible modelica files sections
 */
public enum ModelicaFileSection {
    DECLARATIVE,
    EQUATION,
    ANNOTATION,
    ALGORITHM,
    COMPONENT_DECLARATION,
    COMPONENT_MODIFICATION,
    CLASS_DEFINITION, CONSTRAINING_CLAUSE, EXTENDS_CLAUSE, CLASS_MODIFICATION, REDECLARATION, REDECLARATION_CONSTRAINING_CLAUSE,
}
