package modelica;

/**
 * Enumeration that holds possible class types in parser.Modelica
 */
public enum ModelicaClassType {
	BLOCK, CLASS, CONNECTOR, EXPANDABLE_CONNECTOR, FUNCTION, IMPURE_FUNCTION, MODEL, OPERATOR, OPERATOR_FUNCTION, OPERATOR_RECORD, PACKAGE, PARTIAL_BLOCK, PARTIAL_CLASS, PARTIAL_CONNECTOR, PARTIAL_FUNCTION, PARTIAL_MODEL, PARTIAL_PACKAGE, PARTIAL_RECORD, PURE_FUNCTION, RECORD, TYPE,
}
